### ISSUE TITLE
Available on Linux?

### ISSUE THREAD

**Issue by AtjonTV** [Sigton/bean_rpg#1]
Hello, i was looking around on github and found your project .. i dont know what it is and what it looks like, but in your setup.py i saw that it makes a .exe file, and i have now the question, will your game be available on linux (Debian based Systems)?

If it will be available on linux i will try it for sure!

[I am not fan of Windows so i mainly use Ubuntu, i use Windows only once a month ..]

**Comment by Sigton** [comment]
Sorry, but so far I wasn't planning on building for Linux. This may change in future though.
